### ISSUE TITLE
Problem with msilib

### ISSUE THREAD

**Issue by vilm725** [app-generator/sample-flask-stripe#1]
Hi 👋🏼

I've run docker-compose.yml, but the containers `sample-flask-stripe-001-appseed-app-1` is always `Restarting`. The application doesn't run. When I run a `docker logs sample-flask-stripe-001-appseed-app-1`, I see that (in the end of the logs) :

`[2022-06-06 17:01:57 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/run.py", line 6, in <module>
    from app import app
  File "/app/__init__.py", line 17, in <module>
    from app import views
  File "/app/views.py", line 14, in <module>
    from app.util import get_products, Product, load_product, load_product_by_slug
  File "/app/util.py", line 6, in <module>
    from msilib.schema import Class
ModuleNotFoundError: No module named 'msilib'
[2022-06-06 17:01:57 +0000] [8] [INFO] Worker exiting (pid: 8)
[2022-06-06 17:01:57 +0000] [1] [INFO] Shutting down: Master
[2022-06-06 17:01:57 +0000] [1] [INFO] Reason: Worker failed to boot.`

I've attach all logs
[sample-flask-stripe-001-appseed-app-1.log](https://github.com/app-generator/sample-flask-stripe/files/8846236/sample-flask-stripe-001-appseed-app-1.log)
.

**Comment by kennaparker** [comment]
hi vilm i've got the same issue as you  got, i solve it  by  just putting a comment to the line 6 in util.py like this

##from msilib.schema import Class

**Comment by vilm725** [comment]
Hi @kennaparker 

Sorry for the late, I've a lot of work.
The app "`sample-flask-stripe`" don't work when I comment from msilib.schema import Class. But I've test this application ([flask-soft-ui-dashboard](https://github.com/app-generator/flask-soft-ui-dashboard)), modify the Dockerfile and replace the last ligne with : 
`CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5005" ]`

It's Work ✅

But for "`sample-flask-stripe`", I don't have find a solution.

**Comment by app-generator** [comment]
Hello @kennaparker & @vilm725 

All issues have been fixed in the latest version. 
Really sorry about the support delay. 

We manage 1k+ repos and sometimes the support requests are not seen.
We respond in real-time via Discord and email. 

Contact coordinates are  saved here:
https://discord.gg/fZC6hup

Thank you for using AppSeed products. 
🚀🚀

**Comment by app-generator** [comment]
P.S. A video material that explains how to use the product is available on yTube:  

https://www.youtube.com/watch?v=JDtigUqW_MM
